%% Robot definition 
d1 = 30.25; %cm
d3 = 30.18; %cm
d5 = 31.10; %cm
alpha0 = -15*(pi/180); %deg

%% q0
L(1) = Link('revolute', ...
            'a', 0, ...
            'alpha', alpha0 , ...
            'd', 0, ...
            'offset', 0);
L(1).qlim=[0, 0];   
%% q1
L(2) = Link('revolute', ...
            'a', 0, ...
            'alpha', -pi/2 , ...
            'd', d1, ...
            'offset', -pi/2);
L(2).qlim=[-19*(pi/180), 90*(pi/180)];
     
%% q2
L(3) = Link('revolute', ...
            'a', 0, ...
            'alpha', pi/2 , ...
            'd', 0, ...
            'offset', pi/2);
L(3).qlim = [-90*(pi/180), 41*(pi/180)];

%% q3
L(4) = Link('revolute', ...
            'a', 0, ...
            'alpha', -pi/2 , ...
            'd', d3, ...
            'offset', 0);
L(4).qlim = [-62*(pi/180), 62*(pi/180)];

%% q4
L(5) = Link('revolute', ...
            'a', 0, ...
            'alpha', pi/2 , ...
            'd', 0, ...
            'offset', 0);
L(5).qlim = [-94*(pi/180), 0];

%% q5
L(6) = Link('revolute', ...
            'a', 0, ...
            'alpha', 0 , ...
            'd', d5, ...
            'offset', 0);
L(6).qlim = [-pi, pi];

%% init
lexos = SerialLink(L,'name','l-exos');
clear alpha0 d1 d3 d5 L